# Generated by Django 2.0 on 2020-05-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=254, unique=True)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField(max_length=254, unique=True)),
                ('create_time', models.DateTimeField(db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('spider_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myxitiya.Item')),
            ],
        ),
    ]
