# Generated by Django 2.0 on 2020-05-30 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myxitiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('url', 'type')},
        ),
        migrations.AlterIndexTogether(
            name='item',
            index_together={('type', 'update_time')},
        ),
    ]
